### ISSUE TITLE
Training on CIFAR-10

### ISSUE THREAD

**Issue by san9569** [VITA-Group/Neural-Implicit-Dict#1]
Hi,

I appreciate you sharing your awesome project!

Have you tried to train the NID on the CIFAR-10 dataset?

I've tried that but the convergence is stuck quickly.
If you succeed to train, can you share your experiments setting?

My setting is below

```
batch_size = 64
chunk_size = 32
lr = 1e-4
weight_decay = 0.
num_epochs = 100

num_layers = 4
hidden_dim = 256
num_topk = 64
num_experts = 512
```

Thank you and nice work !

**Comment by peihaowang** [comment]
Hi Sangjin,

I just uploaded a training configuration for CelebA dataset which you may find useful. I think training on full CIFAR-10 gonna be tricky. Instead, I suggest start from one image class first.

Best,
Peihao
