### ISSUE TITLE
Training config

### ISSUE THREAD

**Issue by XiaoqiangZhou** [VITA-Group/Neural-Implicit-Dict#2]
Thanks for sharing the great work.

I try to rerun this code on the CelebA dataset, but I find that the training configs are not provided. Could you please upload the training config for CelebA?

Thanks~

**Comment by thomasXwang** [comment]
Hi @peihaowang,

I am currently trying to reproduce the paper's results as well, and would be interested in the configuration used for obtaining the results on the CelebA dataset
Would you happen to have a good configuration file?
Thank you!

**Comment by peihaowang** [comment]
Hi all,

Sorry for this lengthy delay. I have found a training configuration I used before. I have updated it to this repo. I also uploaded a checkpoint. Please feel free to download and test.

Thanks,
Peihao
