### ISSUE TITLE
Requirements versions 

### ISSUE THREAD

**Issue by thomasXwang** [VITA-Group/Neural-Implicit-Dict#3]
Hi @peihaowang ,
I would like to experiment with your framework, but I am having some trouble with the dependencies mentioned in the repo's Readme
It would greatly help if you could provide the relevant requirements with their corresponding versions (for pip and/or conda) 
Thank you!

**Comment by peihaowang** [comment]
Hi Thomas,

Thanks for your interest. I just had a quick trial. The following versions should work fine:

```
pytorch==1.12.1
torchvision==0.13.1
torchaudio==0.12.1
cudatoolkit=11.3
torch_geometric==2.2.0
```

I'd recommend to use `conda` to setup this environment especially for `torch_geometric`. Feel free to let me know any further questions.

Best,
Peihao
